# Generated by Django 5.2.1 on 2025-05-21 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=30)),
                ('haus_num', models.PositiveSmallIntegerField()),
                ('apartment', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('room_count', models.PositiveSmallIntegerField()),
                ('room_type', models.CharField(choices=[('APARTMENT', 'Apartment'), ('SUITE', 'Suit'), ('SHARED_ROOM', 'Shared room'), ('PRIVATE_ROOM_IN_SHARED', 'Private room in shared'), ('LOFT', 'Loft'), ('STUDIO', 'Studio')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rental', to='booking.address')),
                ('lessor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rental',
                'verbose_name_plural': 'Rentals',
                'db_table': 'rental',
                'ordering': ('-created_at',),
                'unique_together': {('title', 'address')},
            },
        ),
    ]
