# Generated by Django 5.2.1 on 2025-05-22 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_address_city_alter_address_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Check-in Date')),
                ('end_date', models.DateField(verbose_name='Check-out Date')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Cost')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Confirmed')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Cancelled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking.rental', verbose_name='Rental Property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Renter')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'booking',
                'ordering': ('-created_at',),
            },
        ),
    ]
