# Generated by Django 5.2.1 on 2025-05-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked',
            field=models.BooleanField(default=False, verbose_name='Booked'),
        ),
    ]
