# Generated by Django 5.2.1 on 2025-05-26 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='review', to='booking.booking'),
            preserve_default=False,
        ),
    ]
